import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/app/providers/redux-store-provider";
import { Navigation } from "@/shared/ui";
import cn from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";
// After a mutation you should also invalidate the cache by calling revalidatePath or revalidateTag as appropriate.

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navigation />
          <div className="content-container">{children}</div>
        </body>
      </html>
    </StoreProvider>
  );
}
